### ISSUE TITLE
plugin Alexa4P3     : 

### ISSUE THREAD

**Issue by henfri** [smarthomeNG/plugins#300]
Hello,

for this item

```
                type: list
                alexa_device: Lina_Lichterschlauch
                alexa_description: Lichterschlauch Lina Fenster
                alexa_color_value_type: RGB
                alexa_actions: SetColor
                alexa_retrievable: True
                alexa_color_value_type: RGB
                on_change:
                  - og.Lina.FensterFarb.R.Dimmwert = list[0]
                  - og.Lina.FensterFarb.G.Dimmwert = list[1]
                  - og.Lina.FensterFarb.B.Dimmwert = list[2]
                  - og.Lina.FensterFarb.sequencer = 0
```
I get this Error.

```
--
2019-11-25  20:15:08 ERROR    Alexa4P3     Plugin 'alexa4p3' exception in run() method: Alexa: invalid device Lina_Lichterschlauch
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/plugin.py", line 674, in run
    self.plugin.run()
--
    raise ValueError("Alexa: invalid device {}".format(device.id))
ValueError: Alexa: invalid device Lina_Lichterschlauch
```

And the plugin stops responding.

This is a configuration Error, but the Plugin should be resilient against it.

Regards,
Hendrik

**Comment by Andrek01** [comment]
fixed in new release - coming soon

**Comment by msinn** [comment]
Is it fixed with the v1.7 Release?

**Comment by Andrek01** [comment]
Hello Martin,

its not fixed because iḿ too late with the update of the Alexa4P3-Plugin.
It will be ready in the next few weeks.

**Comment by Andrek01** [comment]
Bug is fixed with latest update

**Comment by msinn** [comment]
Closed now, since v1.8 has been released a week ago
